# Generated by Django 5.0.7 on 2024-07-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_name", models.CharField(max_length=90)),
                ("usedby", models.CharField(max_length=90)),
                ("social_image", models.ImageField(upload_to="Social")),
                ("description", models.TextField()),
            ],
        ),
    ]
