# Generated by Django 5.0.7 on 2024-07-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="social",
            old_name="usedby",
            new_name="moreusedby",
        ),
    ]
