# Generated by Django 5.0.7 on 2024-07-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_usedby_social_moreusedby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="social",
            name="description",
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name="social",
            name="moreusedby",
            field=models.CharField(default=True, max_length=90),
        ),
        migrations.AlterField(
            model_name="social",
            name="social_image",
            field=models.ImageField(default=True, upload_to="Social"),
        ),
        migrations.AlterField(
            model_name="social",
            name="social_name",
            field=models.CharField(default=True, max_length=90),
        ),
    ]
