# Generated by Django 5.0.7 on 2024-08-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_social_description_alter_social_moreusedby_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(default=True, max_length=90)),
                ("enter_the_text", models.CharField(default=True, max_length=90)),
            ],
        ),
    ]
