# Generated by Django 5.0.7 on 2024-09-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(null=True)),
                ("output", models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="form",
        ),
    ]
