# Generated by Django 5.0.7 on 2024-10-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_info_delete_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default=True, max_length=90)),
                ("phoneno", models.CharField(default=True, max_length=90)),
                ("email", models.CharField(default=True, max_length=90)),
                ("message", models.TextField(default=True)),
            ],
        ),
    ]
